version: '3.6'

services:
  db:
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trabalho-individual-2021-2
    image: postgres
    container_name: database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
    ports:
     - 5432:5432