name: CI App
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: docker-compose up -d app
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: reset db
        run: docker-compose run app bash -c "rails db:reset"
      - name: test
        run: docker-compose run app bash -c "rspec"
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: install and run lint
        run: docker-compose run app bash -c "gem install rubocop; rubocop"